[package]
name = "hermit-toolkit-viewing-key"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
schemars = "0.7"
base64 = "0.11.0" # Same as used by cosmwas-std
subtle = { version = "2.2.3", default-features = false }
cosmwasm-std = { package = "secret-cosmwasm-std", version = "0.10" }
cosmwasm-storage = { package = "secret-cosmwasm-storage", version = "0.10" }
hermit-toolkit-crypto = { version = "0.1.0", path = "../crypto", default-features = false, features = ["hash", "rand"] }
hermit-toolkit-utils = { version = "0.1.0", path = "../utils"}