[package]
name = "hermit-toolkit-permit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { package = "secret-cosmwasm-std", version = "0.10.1" }

serde = "1.0"
ripemd160 = { version = "0.9.1", default-features = false }
schemars = "0.7"
bech32 = "0.8.1"
remain = "0.2.2"
hermit-toolkit-crypto = { version = "0.1.0", path = "../crypto", features=["hash"] }