[package]
name = "hermit-toolkit-hmip20"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
schemars = "0.7"
cosmwasm-std = { package = "secret-cosmwasm-std", version = "0.10" }
hermit-toolkit-utils = { version = "0.1.0", path = "../utils" }