[package]
name = "hermit-toolkit-serialization"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["json", "bincode2", "base64"]
json = []
base64 = ["schemars"]

[dependencies]
serde = "1.0"
bincode2 = { version = "2.0", optional = true }
schemars = { version = "0.7", optional = true }
cosmwasm-std = { package = "secret-cosmwasm-std", version = "0.10" }

[dev-dependencies]
serde_json = "1"
cosmwasm-schema = { version = "0.9.2" }
